version: '3'

services:
  db:
    image: postgres:11.2-alpine
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
    - .database_data:/var/lib/postgresql/data
  api:
    image: test/trip-planner-api
    ports:
    - 8081:8080
