package lt.vu.trip.entity.response;

public enum ErrorType {
	BE_FAILURE,

	OFFICE_VALIDATION_CAPACITY,
	OFFICE_VALIDATION_TITLE,

	TRIP_VALIDATION_DATE_NOT_PROVIDED,
	TRIP_VALIDATION_DATE_END_BEFORE_NOW,
	TRIP_VALIDATION_DATE_START_BEFORE_NOW,
	TRIP_VALIDATION_DATE_START_AFTER_END,
	TRIP_VALIDATION_OFFICE_REQUIRED,
	TRIP_VALIDATION_OFFICE_SAME,
	TRIP_VALIDATION_OFFICE_DOES_NOT_EXIST,
	TRIP_VALIDATION_PARTICIPANT_DOES_NOT_EXIST,

	OFFICE_NOT_FOUND,

	AUTHENTICATION_USERNAME_NOT_FOUND,
	AUTHENTICATION_INVALID_OR_EXPIRED_TOKEN,
	AUTHENTICATION_ERROR
}
